name: Deploy Guldo to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_HOST: ${{ secrets.VPS_IP }}
      VPS_USER: ${{ secrets.VPS_USERNAME }}
      VPS_SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p $VPS_SSH_PORT $VPS_USER@$VPS_HOST "
            if [ ! -d '/home/ubuntu/guldo' ]; then
              git clone git@github.com:AkiraaCorp/guldo.git /home/ubuntu/guldo
            else
              cd /home/ubuntu/guldo && git pull origin main
            fi
            cat > .env <<EOL
            GO_ENV="development"
            DB_HOST="localhost"
            DB_PORT="5432"
            DB_USER="postgres"
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            DB_NAME="sightbet"
            EOL
            pm2 stop guldo-cron || true
            go build -o guldo main.go
            pm2 start ./guldo --name guldo-cron
          "
